-- Add missing columns to tasks table
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS due_date INTEGER;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS due_time TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS created_at INTEGER DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS updated_at INTEGER DEFAULT CURRENT_TIMESTAMP;

-- Add missing columns to subtasks table
ALTER TABLE subtasks ADD COLUMN IF NOT EXISTS due_date INTEGER;
ALTER TABLE subtasks ADD COLUMN IF NOT EXISTS due_time TEXT;
ALTER TABLE subtasks ADD COLUMN IF NOT EXISTS created_at INTEGER DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE subtasks ADD COLUMN IF NOT EXISTS updated_at INTEGER DEFAULT CURRENT_TIMESTAMP; 